# Generated by Django 2.2.2 on 2019-06-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_description',
            field=models.CharField(default='If you are good at somethin dont do it for free', max_length=100),
            preserve_default=False,
        ),
    ]
